DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS USER_CONNECTIONS;

CREATE TABLE USER (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE TRANSACTION (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sender_id INT NOT NULL,
  receiver_id INT NOT NULL,
  description VARCHAR(255),
  amount DECIMAL(10, 2),

  FOREIGN KEY (sender_id) REFERENCES USER(id) ON DELETE CASCADE,
  FOREIGN KEY (receiver_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE USER_CONNECTIONS (
  user_id INT NOT NULL,
  connected_user_id INT NOT NULL,

  PRIMARY KEY (user_id, connected_user_id),
  FOREIGN KEY (user_id) REFERENCES USER(id),
  FOREIGN KEY (connected_user_id) REFERENCES USER(id)
);
